<?php

namespace Database\Seeders;

use App\Models\Codigo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CodigoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $codigos = [
            [
           'codigo'=>'54A-151-5S1' 
           ],
           [
           'codigo'=>'53B-1T1-53A' 
           ]
           ,
           [
           'codigo'=>'52C-1TX-53A' 
           ]
           ,
           [
           'codigo'=>'DAD-1TS1-53A' 
           ]
           ,
           [
           'codigo'=>'5TB-1T1-53A' 
           ]
           ,
           [
           'codigo'=>'ORB-1T1-5SD' 
           ]
           ,
           [
           'codigo'=>'89S-1TT-83A' 
           ]
           ,
           [
           'codigo'=>'BLE-FA1-73A' 
           ]
           ,
           [
           'codigo'=>'ARM-7TT-544' 
           ]
           ,
           [
           'codigo'=>'5SE-14G-5AA' 
           ]
           ,
           [
           'codigo'=>'MMB-1TR-5GT' 
           ]
           ,
           [
           'codigo'=>'BLA-1E1-53S' 
           ]
           ,
           [
           'codigo'=>'55B-3TA-5MA' 
           ]
           ,
           [
           'codigo'=>'55Z-LO2-78A' 
           ]
           ,
           [
           'codigo'=>'5MU-1JO-5RA' 
           ]
           ,
           [
           'codigo'=>'5EL-1SR-5UY' 
           ]
           ,
           [
           'codigo'=>'5CO-1KI-32A' 
           ]
           ,
           [
           'codigo'=>'EL8-5HU-57A' 
           ]
           ,
           [
           'codigo'=>'785-1BO-89A' 
           ]
           ,
           [
           'codigo'=>'589-7T1-5BA' 
           ]
           ,
           [
           'codigo'=>'777-787-977' 
           ]
           ,
           [
           'codigo'=>'788-HH7-UI7' 
           ]
           ,
           [
           'codigo'=>'LAT-787-7OM' 
           ]
           ,
           [
           'codigo'=>'LAD-ORM-COL' 
           ],
           [
           'codigo'=>'INF-530-4L7' 
           ],
           [
           'codigo'=>'7FD-7FD-OMG' 
           ],
           [
           'codigo'=>'7HT-IO7-MAR' 
           ],
           [
           'codigo'=>'7SD-677-TRU' 
           ],
           [
           'codigo'=>'798-789-789' 
           ],
           [
           'codigo'=>'78S-7T7-7YU' 
           ],
           [
           'codigo'=>'78T-TTT-7HU' 
           ],
           [
           'codigo'=>'75S-T1T-111' 
           ],
           [
           'codigo'=>'111-7G3-FFF' 
           ],
           [
           'codigo'=>'7LA3-MEJ-755' 
           ],
           [
           'codigo'=>'999-7T7-IUU' 
           ],
           [
           'codigo'=>'RR3-DD3-MM3' 
           ],
           [
           'codigo'=>'AY3-PEL-OLS' 
           ],
           [
           'codigo'=>'MEJ-YA6-INU' 
           ],
           [
           'codigo'=>'ONU-7SD-7BO' 
           ],
           [
           'codigo'=>'7ES-TA7-ESU' 
           ],
           [
           'codigo'=>'QQQ-7S1-111' 
           ],
           [
           'codigo'=>'XD3-7D7-6YU' 
           ],
           [
           'codigo'=>'7MA-447-444' 
           ],
           [
           'codigo'=>'JII-UUU-333' 
           ],
           [
           'codigo'=>'OII-LL4-UUU' 
           ]

        ];
        foreach ($codigos as $codigos) {
            Codigo::create($codigos);
        }

    }
}
